server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 5201314hyq
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml